### ISSUE TITLE
Random segfaults with rspec and webmock

### ISSUE THREAD

**Issue by samstickland** [sporkmonger/addressable#305] opened 2018-07-13 23:00 UTC
Hi,

On my Mac I am getting random segfaults.

Any idea how I should go about debugging this?

It seems we only have this problem OS X, it's not reported on Ubuntu or Codeship.

```/Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/addressable-2.5.2/lib/addressable/idna/pure.rb:156: [BUG] Segmentation fault at 0x00007000022f93d0
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0054 p:0070 s:0285 e:000284 BLOCK  /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/addressable-2.5.2/lib/addressable/idna/pure.rb:156 [FINISH]
c:0053 p:---- s:0281 e:000280 CFUNC  :each
c:0052 p:0011 s:0277 e:000276 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/activesupport-5.1.6/lib/active_support/core_ext/range/each.rb:5
c:0051 p:0061 s:0272 e:000271 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/addressable-2.5.2/lib/addressable/idna/pure.rb:147
c:0050 p:0044 s:0258 e:000257 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/addressable-2.5.2/lib/addressable/idna/pure.rb:119
c:0049 p:0295 s:0252 e:000250 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/addressable-2.5.2/lib/addressable/uri.rb:539
c:0048 p:0028 s:0241 e:000240 BLOCK  /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/addressable-2.5.2/lib/addressable/uri.rb:1502 [FINISH]
c:0047 p:---- s:0237 e:000236 CFUNC  :map
c:0046 p:0079 s:0233 e:000232 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/addressable-2.5.2/lib/addressable/uri.rb:1501
c:0045 p:0044 s:0227 e:000226 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/addressable-2.5.2/lib/addressable/uri.rb:827
c:0044 p:0012 s:0223 e:000222 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/webmock-3.4.2/lib/webmock/util/uri.rb:37
c:0043 p:0016 s:0214 e:000213 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/webmock-3.4.2/lib/webmock/request_pattern.rb:143
c:0042 p:0060 s:0209 e:000208 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/webmock-3.4.2/lib/webmock/request_pattern.rb:37
c:0041 p:0011 s:0203 e:000202 BLOCK  /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/webmock-3.4.2/lib/webmock/stub_registry.rb:58 [FINISH]
c:0040 p:---- s:0199 e:000198 IFUNC
c:0039 p:---- s:0196 e:000195 CFUNC  :each
c:0038 p:---- s:0193 e:000192 CFUNC  :detect
c:0037 p:0015 s:0189 e:000188 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/webmock-3.4.2/lib/webmock/stub_registry.rb:57
c:0036 p:0006 s:0184 e:000183 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/webmock-3.4.2/lib/webmock/stub_registry.rb:50
c:0035 p:0060 s:0178 e:000177 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:79
c:0034 p:0009 s:0167 e:000166 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/http/default.rb:121
c:0033 p:0026 s:0162 e:000161 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/http/default.rb:76
c:0032 p:0207 s:0149 e:000148 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/http/common.rb:62
c:0031 p:0149 s:0140 e:000139 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/bridge.rb:164
c:0030 p:0010 s:0131 e:000130 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/oss/bridge.rb:579
c:0029 p:0008 s:0126 e:000125 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/remote/oss/bridge.rb:522
c:0028 p:0010 s:0121 e:000120 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/common/element.rb:189
c:0027 p:0008 s:0117 e:000115 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/selenium/node.rb:139
c:0026 p:0008 s:0112 e:000111 BLOCK  /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/node/element.rb:301
c:0025 p:0020 s:0109 e:000108 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/node/base.rb:78
c:0024 p:0005 s:0100 e:000099 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/node/element.rb:301 [FINISH]
c:0023 p:---- s:0096 e:000095 IFUNC
c:0022 p:0022 s:0093 e:000091 BLOCK  /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/result.rb:44 [FINISH]
c:0021 p:---- s:0088 e:000087 CFUNC  :loop
c:0020 p:0028 s:0084 e:000083 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/result.rb:41 [FINISH]
c:0019 p:---- s:0079 e:000078 CFUNC  :select
c:0018 p:0020 s:0075 e:000074 BLOCK  /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/selector.rb:274 [FINISH]
c:0017 p:0158 s:0069 e:000068 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/selector/filters/base.rb:45
c:0016 p:0012 s:0061 e:000060 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/selector/filters/node_filter.rb:10
c:0015 p:0056 s:0054 e:000053 BLOCK  /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/queries/selector_query.rb:139 [FINISH]
c:0014 p:---- s:0049 e:000048 IFUNC
c:0013 p:---- s:0046 e:000045 CFUNC  :each
c:0012 p:---- s:0043 e:000042 CFUNC  :all?
c:0011 p:0024 s:0039 e:000038 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/queries/selector_query.rb:131
c:0010 p:0123 s:0033 e:000032 METHOD /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/queries/selector_query.rb:57
c:0009 p:0008 s:0028 e:000027 BLOCK  /Users/samuelstickland/.rvm/gems/ruby-2.5.1/gems/capybara-3.3.1/lib/capybara/result.rb:29 [FINISH]
c:0008 p:---- s:0024 e:000023 IFUNC
c:0007 p:---- s:0021 e:000020 CFUNC  :each
c:0006 p:---- s:0018 e:000017 CFUNC  :each
c:0005 p:---- s:0015 e:000014 IFUNC
c:0004 p:---- s:0012 E:0015a0 CFUNC  :each
c:0003 p:---- s:0009 e:000008 CFUNC  :each
c:0002 p:---- s:0006 E:0024d0 IFUNC
c:0001 p:---- s:0003 e:000002 (none) [FINISH]
```

**Comment by dentarg** [comment] 2018-07-17 07:57
I don't think there is much that can be done if we can not somewhat reliably reproduce the segfaults, see other recent issue about segfaults: #290 (also webmock involved)

And another much older issue (rspec involved): https://github.com/sporkmonger/addressable/issues/95

And lastly, the oldest segfault issue (might give some clude?) https://github.com/sporkmonger/addressable/issues/20

(Now I linked every old issue from https://github.com/sporkmonger/addressable/issues?utf8=%E2%9C%93&q=is%3Aissue+segfault)

**Comment by dentarg** [comment] 2018-07-17 08:07
Leaving some source code links from my spelunking 

https://github.com/bblimke/webmock/blob/v3.4.2/lib/webmock/util/uri.rb#L37
https://github.com/sporkmonger/addressable/blob/addressable-2.5.2/lib/addressable/idna/pure.rb
https://github.com/rails/rails/blob/v5.1.6/activesupport/lib/active_support/core_ext/range/each.rb

**Comment by dentarg** [comment] 2018-07-17 08:37
I wonder if it is something likes this https://github.com/google/protobuf/pull/3560#issuecomment-325771513 that is happening

**Comment by dentarg** [comment] 2018-07-17 08:43
Related? https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1979 see the ruby bugs linked

**Comment by dentarg** [comment] 2018-07-17 08:48
@samstickland do you have the full crash report? I think there should be more sections besides "Control frame information". Would be good to be able to compare reports posted in https://bugs.ruby-lang.org/issues/14334 and https://bugs.ruby-lang.org/issues/14561

**Comment by sporkmonger** [comment] 2019-08-31 03:22
I'm going to close this as obsolete since I'm cutting a new release.

**Closed by sporkmonger** 2019-08-31 03:22 UTC
