### ISSUE TITLE
Addressable::URI::InvalidURIError with valid URLs

### ISSUE THREAD

**Issue by crondaemon** [sporkmonger/addressable#390] opened 2020-05-07 15:58 UTC
Hi
I'm experiencing issues with URLs containing `?//`. Simple reproducer:

```ruby
irb(main):004:0> a = Addressable::URI.parse("http://a.domain.it/?p1=v1&p2=v2")
=> #<Addressable::URI:0x2aeb31315708 URI:http://a.domain.it/?p1=v1&p2=v2>
irb(main):005:0> a.join("/?p1=v1&p2=v2")
=> #<Addressable::URI:0x2aeb313120d0 URI:http://a.domain.it/?p1=v1&p2=v2>
irb(main):006:0> 
```
works as expected. Instead:

```ruby
irb(main):002:0> a = Addressable::URI.parse("http://a.domain.it//?p1=v1&p2=v2")
=> #<Addressable::URI:0x2aeb3135450c URI:http://a.domain.it//?p1=v1&p2=v2>
irb(main):003:0> a.join("//?p1=v1&p2=v2")
Traceback (most recent call last):
        1: from (irb):3
Addressable::URI::InvalidURIError (Absolute URI missing
hierarchical segment: 'http://?p1=v1&p2=v2')
```

If I'm not mistaken the latter is a valid URL.

**Comment by dentarg** [comment] 2020-05-07 16:35
> If I'm not mistaken the latter is a valid URL.

Exactly what string are you saying is a valid URL?

---

I started looking at the humongous that's `#join`

https://github.com/sporkmonger/addressable/blob/5c04c79cdc8da2de5f15782641a7f102e2627a4b/lib/addressable/uri.rb#L1876-L1975

I could spot this difference that's probably of importance

```ruby
irb(main):024:0> Addressable::URI.parse("//?p1=v1&p2=v2").path
=> ""
irb(main):025:0> Addressable::URI.parse("/?p1=v1&p2=v2").path
=> "/"
```

Feel free to dig in yourself :)

**Comment by crondaemon** [comment] 2020-05-07 16:41
I'm saying this `http://a.domain.it//?p1=v1&p2=v2` is a valid URL.

**Comment by crondaemon** [comment] 2020-05-07 16:42
According to this https://www.freeformatter.com/url-parser-query-string-splitter.html the URL should be formally corrent, hence the join should work with both `http://a.domain.it//?p1=v1&p2=v2` and `http://a.domain.it/?p1=v1&p2=v2`.

**Comment by dentarg** [comment] 2020-05-07 18:17
This works:

```ruby
irb(main):033:0> Addressable::URI.parse("http://a.domain.it//?p1=v1&p2=v2").join("http://a.domain.it/?p1=v1&p2=v2")
=> #<Addressable::URI:0x3fe2e485c33c URI:http://a.domain.it/?p1=v1&p2=v2>
irb(main):034:0> Addressable::URI.parse("http://a.domain.it/?p1=v1&p2=v2").join("http://a.domain.it//?p1=v1&p2=v2")
=> #<Addressable::URI:0x3fe2ecc68540 URI:http://a.domain.it//?p1=v1&p2=v2>
```

**Comment by crondaemon** [comment] 2020-05-07 20:13
Unfortunately this doesn't come from a call I made myself but from `em-http-client`. I opened a bug there at first (igrigorik/em-http-request#338), but then I realized it looked like a bug in Addressable and I opened this.

AFAIK, this

```
Addressable::URI.parse("http://a.domain.it//?p1=v1&p2=v2").join("//?p1=v1&p2=v2")
```

should work and it doesn't. If the above call is wrong, then the bug is in `em-http-client`, then I will reopen my bug there.

Going deeper in the code it looks to me that when building an Addressable if the `host` part is not specified, the `proto` part doesn't make sense.

**Comment by sporkmonger** [comment] 2020-06-02 06:00
This is working exactly as it's supposed to. Please carefully review section 5.2: https://tools.ietf.org/html/rfc3986#section-5.2

There are extensive test cases for this, including some taken from the RFC itself, though unfortunately I don't think there's an example directly analogous to the one you've provided. However the implementation for resolving a URL is pretty clearly spelled out in the RFC and the implementation here should follow it quite closely.

I believe in this case what's happening is that you've misunderstood how the second URI will be parsed and based on that misunderstanding, it could appear like there's a bug. However if you were to build the second URI from component pieces instead of trying to parse it, I believe that that would give you the expected behavior.

i.e. if instead of doing a parse you did something like `uri.path = "//?p1=v1&p2=v2"` and then join that URI to the first, now I believe you should get the expected result. However, starting from an unparsed string, it is correct to parse the second URI as a network-relative path. That may not have been your expectation or intention, but it is correct to have done that. Joining a URI to a network-relative path will replace the original URI, only keeping the scheme component and throwing away everything else.

Network relative paths are most commonly used on web pages that are served under both `http` and `https` schemes, where the content is static, and an external reference must be linked to. Since browsers may give warnings if an `https` page links to external content served under `http` but the content is static, a network relative path is used instead to ensure that the browser will resolve the absolute path but keep the same scheme.

**Closed by sporkmonger** 2020-06-02 06:00 UTC
