### ISSUE TITLE
Encoding is changed through normalisation

### ISSUE THREAD

**Issue by ghost** [sporkmonger/addressable#100] opened 2013-01-06 03:37 UTC
Encoding is changed when URL's are normalised. 

```
require 'rubygems'
require 'addressable/uri'

Addressable::URI.parse('http://www.google.com').scheme.encoding
=> #<Encoding:UTF-8>
Addressable::URI.parse('http://www.google.com').normalize.scheme.encoding
=> #<Encoding:ASCII-8BIT>
```

**Comment by dentarg** [comment] 2023-04-01 11:08
Can't reproduce with the latest three releases (this was with Ruby 3.2.1 in macOS Monterey)

```ruby
$ irb -raddressable
irb(main):001:0> Addressable::VERSION::STRING
=> "2.8.2"
irb(main):002:0> Addressable::URI.parse('http://www.google.com').scheme.encoding
=> #<Encoding:UTF-8>
irb(main):003:0> Addressable::URI.parse('http://www.google.com').normalize.scheme.encoding
=> #<Encoding:UTF-8>

$ irb -raddressable
irb(main):001:0> Addressable::VERSION::STRING
=> "2.8.1"
irb(main):002:0> Addressable::URI.parse('http://www.google.com').scheme.encoding
=> #<Encoding:UTF-8>
irb(main):003:0> Addressable::URI.parse('http://www.google.com').normalize.scheme.encoding
=> #<Encoding:UTF-8>

$ irb -raddressable
irb(main):001:0> Addressable::VERSION::STRING
=> "2.8.0"
irb(main):002:0> Addressable::URI.parse('http://www.google.com').scheme.encoding
=> #<Encoding:UTF-8>
irb(main):003:0> Addressable::URI.parse('http://www.google.com').normalize.scheme.encoding
=> #<Encoding:UTF-8>
```

I even tried with Ruby 2.4 in Docker [that does not set `LANG`](https://github.com/weppos/publicsuffix-ruby/issues/118#issuecomment-774003098)

```bash
$ docker run --rm -it ruby:2.4-slim-buster bash
Unable to find image 'ruby:2.4-slim-buster' locally
2.4-slim-buster: Pulling from library/ruby
a6c32b8bc1ce: Pull complete
7db939dca181: Pull complete
44ee92a98491: Pull complete
05646eb57c6f: Pull complete
985a33ca6285: Pull complete
Digest: sha256:ac34ee3f02c12e9c6fdfa2164bd7f98e579ef59e6f0838d1b9befb427489d058
Status: Downloaded newer image for ruby:2.4-slim-buster
root@cea9b00c2447:/# gem install addressable
Fetching addressable-2.8.2.gem
Fetching public_suffix-5.0.1.gem
ERROR:  Error installing addressable:
	The last version of public_suffix (>= 2.0.2, < 6.0) to support your Ruby & RubyGems was 4.0.7. Try installing it with `gem install public_suffix -v 4.0.7` and then running the current command again
	public_suffix requires Ruby version >= 2.6. The current ruby version is 2.4.10.364.
root@cea9b00c2447:/# gem install public_suffix -v 4.0.7
Fetching public_suffix-4.0.7.gem
Successfully installed public_suffix-4.0.7
1 gem installed
root@cea9b00c2447:/# gem install addressable
Successfully installed addressable-2.8.2
1 gem installed
root@cea9b00c2447:/# irb -raddressable
irb(main):001:0> Addressable::VERSION::STRING
=> "2.8.2"
irb(main):002:0> RUBY_VERSION
=> "2.4.10"
irb(main):003:0> Addressable::URI.parse('http://www.google.com').scheme.encoding
=> #<Encoding:US-ASCII>
irb(main):004:0> Addressable::URI.parse('http://www.google.com').normalize.scheme.encoding
=> #<Encoding:UTF-8>
```

I think we can close this.

**Closed by dentarg** 2023-04-01 11:08 UTC
Labels: Accepted
