### ISSUE TITLE
Update to 2.8.2 break test env

### ISSUE THREAD

**Issue by le0pard** [sporkmonger/addressable#502] opened 2023-04-04 20:40 UTC
After update to version 2.8.2 test env broken with such errors.

```bash
NoMethodError:
       undefined method `to_str' for :step:Symbol
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:900:in `normalize_value'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:908:in `block in normalize_value'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:907:in `each'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:907:in `inject'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:907:in `normalize_value'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:774:in `block in transform_capture'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:756:in `each'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:756:in `inject'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:756:in `transform_capture'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:595:in `block in expand'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:594:in `gsub!'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/addressable-2.8.2/lib/addressable/template.rb:594:in `expand'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/site_prism-3.7.3/lib/site_prism/page.rb:101:in `url'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/site_prism-3.7.3/lib/site_prism/page.rb:151:in `load_html_website'
     # /Users/leo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/site_prism-3.7.3/lib/site_prism/page.rb:66:in `load'
```

Downgrade to 2.8.1 fix this issue

**Comment by dentarg** [comment] 2023-04-04 21:14
Duplicate of https://github.com/sporkmonger/addressable/issues/498

Fixed in Addressable 2.8.3

**Closed by dentarg** 2023-04-04 21:14 UTC
Labels: Duplicate
