### ISSUE TITLE
URI Parse Error

### ISSUE THREAD

**Issue by michaeltelford** [sporkmonger/addressable#376] opened 2020-01-22 21:28 UTC
I'm running `ruby 2.5.3` and `addressable 2.7.0`.

Consider the following:

```sh
[1] pry(main)> Addressable::URI.parse 'http://'
Addressable::URI::InvalidURIError: Absolute URI missing hierarchical segment: 'http://'
from /home/michael/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/addressable-2.7.0/lib/addressable/uri.rb:2449:in `validate'
```

Some might argue that it's OK to fail here because `http://` is indeed an invalid URL. However, so is the following, which parses successfully:

```sh
[2] pry(main)> Addressable::URI.parse '!'
=> #<Addressable::URI:0x1316fe0 URI:!>
```

In the interest of making the code as robust as possible, is it not best to support the parsing of `http://` (and `https://`)? My program extracts links from webpages before parsing them with `Addressable::URI.parse`. Since you get all sorts of crap on the web, it would be good to be able to support this scenario in Addressable rather than me having to implement a work-a-round.

**Comment by dentarg** [comment] 2020-01-23 10:05
> My program extracts links from webpages before parsing them with `Addressable::URI.parse`. Since you get all sorts of crap on the web, it would be good to be able to support this scenario in Addressable rather than me having to implement a work-a-round.

I understand where you are coming from. A `sane?` method has been discussed before to do this:

* https://github.com/sporkmonger/addressable/issues/198#issuecomment-226335478
* https://github.com/twingly/twingly-url/issues/74#issuecomment-226334749

Feel free to check out https://github.com/twingly/twingly-url, I think it can handle your cases:

```ruby
irb(main):004:0> Twingly::URL.parse("https://")
=> #<Twingly::URL::NullURL:0x00007fe6dc981258>
irb(main):005:0> Twingly::URL.parse("http://")
=> #<Twingly::URL::NullURL:0x00007fe6dca1b9c0>
irb(main):006:0> Twingly::URL.parse("!")
=> #<Twingly::URL::NullURL:0x00007fe6dca134a0>
irb(main):007:0> Twingly::URL.parse("!").valid?
=> false
```

(Note that some things (like the normalization) in twingly-url is purposefully built according to specific needs from Twingly (I work there))

**Comment by dentarg** [comment] 2020-01-23 10:07
I will close this as a duplicate of https://github.com/sporkmonger/addressable/issues/257

**Closed by dentarg** 2020-01-23 10:07 UTC

**Comment by michaeltelford** [comment] 2020-01-25 13:19
Hi @dentarg,

Thanks for your comments. With respect, this issue isn't a duplicate of #257. I don't want an `is_parsable?` method etc. I want `Addressable::URI.parse` to successfully parse `http://` and `https://` strings; in the same way that `parse` works with the string `!` (which is also invalid as far as URLs go).

The twingly-url gem looks cool but I'm already using addressable-uri and would prefer not to have to swap out dependencies and update my code base accordingly. Up until now, addressable-uri hasn't caused me any issues.

**Comment by dentarg** [comment] 2020-01-25 15:29
Okay, I see. 

This issue will stay closed because the behaviour you are seeing is intentional, see  https://github.com/sporkmonger/addressable/issues/216#issuecomment-159473504 for an explanation.

`!` works because it is considered relative, not absolute:

```ruby
$ irb -r addressable/uri
irb(main):001:0> Addressable::URI.parse("!")
=> #<Addressable::URI:0x3fd5d486a774 URI:!>
irb(main):002:0> Addressable::URI.parse("!").relative?
=> true
```

**Comment by michaeltelford** [comment] 2020-01-25 16:56
Are there any other Strings (besides `http://` and `https://`) that will cause an error upon `parse`? The fuller list I have the better work-a-round I can code in my application. Thanks.

**Comment by dentarg** [comment] 2020-01-25 18:19
I don't know, but feel free to read the source code. :-)

**Comment by dentarg** [comment] 2020-01-25 18:21
@michaeltelford Also, feel free to take a look here: https://github.com/twingly/twingly-url/blob/bf5fa7ba54fa212a04f7aa8fdc77c92927c4c361/spec/lib/twingly/url_spec.rb#L7-L52
